---
title: "Regression to test initial hypothesis (more links better sustainability)"
author: "AlexSh"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: word_document
---

```{r load libraries}
library(tidyverse)
library(knitr)
library(rmarkdown)
library(readxl)
library(ggplot2)
library(dplyr)
library(tidyr)
library(readr)
```


```{r}
# download network data of construction companies
splc <- read_excel("../data/raw/SPLC_NA.xlsx", sheet=2)
# exclude NAs, convert column to numeric
splc <- splc %>% 
  filter(Ticker != "BDGI CN" & Ticker != 'J US') %>% 
  mutate(Number = as.numeric(Number))
```


```{r data visualization}
# aggregated connections of each ticker
splc %>% 
  group_by(Year,Ticker) %>% 
  summarise(Number = sum(Number)) %>%
  ggplot(aes(x = Year, y = Number, color = Ticker)) +
  geom_line()

# aggregated connections
splc %>% 
  group_by(Year) %>% 
  summarize(Number = sum(Number)) %>% 
  ggplot(aes(x = Year, y = Number)) +
  geom_line()

# connections with customer&supplier
splc %>% 
  group_by(Year,Type) %>% 
  summarize(Number = sum(Number)) %>% 
  ggplot(aes(x = Year, y = Number, color = Type)) + 
  geom_line()

# tickers with high supply chain
splc %>% 
  group_by(Ticker) %>% 
  filter(mean(Number) >= 17) %>%
  group_by(Year,Ticker) %>% 
  summarise(Number = sum(Number)) %>%
  ggplot(aes(x = Year, y = Number, color = Ticker)) +
  geom_line()

# tickers with low supply chain
splc %>% 
  group_by(Ticker) %>% 
  filter(mean(Number) < 17) %>%
  group_by(Year,Ticker) %>% 
  summarise(Number = sum(Number)) %>%
  ggplot(aes(x = Year, y = Number, color = Ticker)) +
  geom_line()
```

```{r download dep var}
# download sustainability data
sus <- read_excel("../data/raw/C&S.xlsx") %>% 
  filter(Country %in% c('CANADA','UNITED STATES')) %>% 
  mutate_at(5:ncol(.),as.numeric) %>%
# exclude Tickets without any sustainability data
  filter(!rowSums(is.na(.[,5:ncol(.)])) == ncol(.)-4) %>% 
# exclude all ESG Disclosure Score data
  select(-c(RX317_FY2013,RX317_FY2014,
            RX317_FY2015,RX317_FY2016,
            RX317_FY2016,RX317_FY2017,
            RX317_FY2018,RX317_FY2019,
            RX317_FY2020,RX317_FY2021))
```

```{r clean dep var}
# remove Tickers with all NAs
sus <- sus %>% 
  filter(!rowSums(is.na(.[,5:ncol(.)])) == ncol(.)-4)
# keep companies without NAs
sus <- sus %>% 
  filter(!Ticker %in% c("FTDR US", "DY US"))
```

```{r change dep var to long}
# format to long
sus_long <- sus %>%
  pivot_longer(cols = starts_with("SR"), 
               names_to = "variable", 
               values_to = "value") %>%
  separate(variable, 
           c("SR_variable", "Year"), 
           sep = "_FY") %>%
  mutate(Year = as.numeric(Year)) %>% 
  pivot_wider(names_from = SR_variable, 
              values_from = value)

# add number of suppliers to number of customers
splc_aggr <- splc %>% 
  group_by(Ticker,Year) %>% 
  summarize(Number = sum(Number))
```


```{r merge dep with indep var}
# merge with network data
merged_df <- left_join(sus_long, splc_aggr, by = c('Year' = 'Year', 'Ticker' = 'Ticker'))
remove(sus,sus_long,splc,splc_aggr)

# exclude Tickers with NAs in Number
merged_df <- merged_df %>% 
  filter(!Ticker %in% c('J US', 'BLD US'))
```

```{r correlation}
# correlation analysis
sr_cols <- grep('^SR', names(merged_df), value = T)
correlations <- sapply(sr_cols, function(x) 
                       cor(merged_df[[x]],merged_df$Number))
correlations <- sapply(sr_cols, function(x) cor(merged_df[[x]], merged_df$Number))

cor_df <- data.frame(SR_variable = sr_cols, Correlation = correlations)

# display in table format
kable(cor_df)
```



